### ISSUE TITLE
Upgrade to elm 0.19

### ISSUE THREAD

**Issue by jhrcek** [elm-community/graph#20] opened 2018-08-26 14:41 UTC
Hello @sgraf812,
now that elm 0.19 it would be nice to have this library upgraded for it.

So far I tried [elm-upgrade](https://github.com/avh4/elm-upgrade) which resolves most of the dependency/core functions renaming. After that some manual steps are needed:

- [ ]  get rid of variable shadowing (simple)
- [ ] Remove occurrences of `Debug.crash` (in some cases I'm unsure how to proceed)
- [ ] Migrate tests to the new `elm-explorations/test` (should be simple too).

Are you planning to work on that in the weeks to come? If not I could start working on it, but I'd ask for some input regarding those `Debug.crash`es.

**Comment by sgraf812** [comment] 2018-08-26 17:42
I'd love if you would take the lead on this.

**Comment by jschomay** [comment] 2018-08-27 02:06
I need this too!  I've upgraded a few libraries already, so I'll give it a shot.

**Comment by jschomay** [comment] 2018-08-27 04:59
Ok, I've got it all updated and running.  There were a few tricky parts, but I *think* it works as intended.  I did have to make a major semvar changes though on a few function's signatures (see the PR comments).

**Comment by sgraf812** [comment] 2018-08-29 11:18
Fixed in #21, incurring a new dependency on `elm/json`.

**Closed as completed by sgraf812** 2018-08-29 11:18 UTC
